// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVbmFx7-r_Na5Mz7qUKql7AedjNMH3haA',
    appId: '1:139109314186:web:39f5cd06188e298ebec773',
    messagingSenderId: '139109314186',
    projectId: 'everdell-c4fad',
    authDomain: 'everdell-c4fad.firebaseapp.com',
    storageBucket: 'everdell-c4fad.appspot.com',
    measurementId: 'G-Q4NPS2BS09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApLM4uTs-WFZYHAGpFLJMXCWFgbTMX-_A',
    appId: '1:139109314186:android:3802100c0f262171bec773',
    messagingSenderId: '139109314186',
    projectId: 'everdell-c4fad',
    storageBucket: 'everdell-c4fad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyRbVwSv_rqpwrdC8X_hsEvTv0xuDOS2Q',
    appId: '1:139109314186:ios:5c49ea4c8fbab696bec773',
    messagingSenderId: '139109314186',
    projectId: 'everdell-c4fad',
    storageBucket: 'everdell-c4fad.appspot.com',
    iosClientId: '139109314186-aa6h91ae30rc4uckq54s2t9tcvhr56h1.apps.googleusercontent.com',
    iosBundleId: 'com.example.everdellApp31822',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyRbVwSv_rqpwrdC8X_hsEvTv0xuDOS2Q',
    appId: '1:139109314186:ios:d9ac7beadaa4a860bec773',
    messagingSenderId: '139109314186',
    projectId: 'everdell-c4fad',
    storageBucket: 'everdell-c4fad.appspot.com',
    iosClientId: '139109314186-d2m61jp2r9gt5r1lqhu49ohp1k9mucev.apps.googleusercontent.com',
    iosBundleId: 'com.example.everdellApp',
  );
}
